Dev-roll/capture-the-task

- .idea/git_toolbox_prj.xml
- .idea/gradle.xml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/capturethetask/CttApp.kt
- app/src/main/java/com/example/capturethetask/CttApplication.kt
- app/src/main/java/com/example/capturethetask/MainActivity.kt
- app/src/main/java/com/example/capturethetask/model/AppContainer.kt
- app/src/main/java/com/example/capturethetask/model/Task.kt
- app/src/main/java/com/example/capturethetask/model/TaskDao.kt
- app/src/main/java/com/example/capturethetask/model/TaskDatabase.kt
- app/src/main/java/com/example/capturethetask/model/TasksRepository.kt
- app/src/main/java/com/example/capturethetask/model/TasksRepositoryImpl.kt
- app/src/main/java/com/example/capturethetask/ui/AppViewModelProvider.kt
- app/src/main/java/com/example/capturethetask/ui/capture/CaptureViewModel.kt
- app/src/main/java/com/example/capturethetask/ui/capture/homeScreen.kt
- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryScreen.kt
- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryViewModel.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeViewModel.kt
- app/src/main/java/com/example/capturethetask/ui/navigation/CttNavGraph.kt
- app/src/main/java/com/example/capturethetask/ui/navigation/NavigationDestination.kt
- app/src/main/java/com/example/capturethetask/ui/theme/Color.kt
- app/src/main/java/com/example/capturethetask/ui/theme/Shape.kt
- app/src/main/java/com/example/capturethetask/ui/theme/Theme.kt
- app/src/main/java/com/example/capturethetask/ui/theme/Type.kt
- app/src/main/res/values/strings.xml
- build.gradle
- Close #1
```
[x] Yes
[ ] No
```
-
> feat: タスク登録画面を作成

- app/src/main/java/com/example/capturethetask/ui/AppViewModelProvider.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeViewModel.kt
- app/src/main/java/com/example/capturethetask/ui/navigation/CttNavGraph.kt
- app/src/main/res/values/strings.xml
- Close #3
```
[x] Yes
[ ] No
```
-
> feat: タスクの一覧を表示

- app/src/main/java/com/example/capturethetask/model/TaskDao.kt
- app/src/main/java/com/example/capturethetask/model/TasksRepository.kt
- app/src/main/java/com/example/capturethetask/model/TasksRepositoryImpl.kt
- Close #12
```
[x] Yes
[ ] No
```
-
> feat: 完了のフラグを変更する関数を作成

- app/src/main/java/com/example/capturethetask/model/TaskDao.kt
- Close #14
```
[x] Yes
[ ] No
```
-
> fix: `updateCompleted`のタイポを修正

- app/build.gradle
- app/src/main/java/com/example/capturethetask/MainActivity.kt
- app/src/main/java/com/example/capturethetask/ui/capture/CaptureScreen.kt
- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryScreen.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- app/src/main/java/com/example/capturethetask/ui/navigation/CttNavGraph.kt
- Close #9
```
[x] Yes
[ ] No
```
-
> feat: ボタンのデザイン・挙動の変更

- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeViewModel.kt
- Close #18
```
[x] Yes
[ ] No
```
-
> feat: タスク完了処理を実装

- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryScreen.kt
- Close #10
```
[x] Yes
[ ] No
```
-
> feat: タスク情報入力画面のデザイン

- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- Close #
```
[x] Yes
[ ] No
```
-
> feat: check icon

- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- Close #24
```
[x] Yes
[ ] No
```
-
> fix: itemをtaskに修正

- app/src/main/java/com/example/capturethetask/model/Task.kt
- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryViewModel.kt
- Close #21
```
[x] Yes
[ ] No
```
-
> feat: Task に不足したプロパティを追加

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/capturethetask/ui/capture/CaptureScreen.kt
- build.gradle
- Close #28
```
[x] Yes
[ ] No
```
-
> feat: 権限のリクエストを要求する

- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryScreen.kt
- Close #26
```
[x] Yes
[ ] No
```
-
> feat: 入力形式を変更

- app/src/main/java/com/example/capturethetask/model/TaskDao.kt
- app/src/main/java/com/example/capturethetask/model/TasksRepository.kt
- app/src/main/java/com/example/capturethetask/model/TasksRepositoryImpl.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeViewModel.kt
- Close #
```
[x] Yes
[ ] No
```
-
> feat: add star

- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryScreen.kt
- Close #32
```
[x] Yes
[ ] No
```
-
> chore: キーボードのボタン

- app/build.gradle
- app/src/main/java/com/example/capturethetask/ui/capture/CaptureScreen.kt
- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryScreen.kt
- app/src/main/java/com/example/capturethetask/ui/navigation/CttNavGraph.kt
- Close #7
```
[x] Yes
[ ] No
```
-
> feat: カメラ機能を実装

- app/build.gradle
- app/src/main/java/com/example/capturethetask/ui/entry/TaskEntryScreen.kt
- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- Close #35
```
[ ] Yes
[ ] No
```
- @notchcoder `HomeScreen.kt` 内のTODO箇所
> feat: パスから画像を表示

- app/src/main/java/com/example/capturethetask/ui/capture/CaptureScreen.kt
- Close #37
```
[x] Yes
[ ] No
```
-
> feat: capture画面のFABのonclickを実装

- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- Close #23
```
[x] Yes
[ ] No
```
-
> feat: ローカルの画像を表示

- app/src/main/java/com/example/capturethetask/ui/theme/Color.kt
- app/src/main/java/com/example/capturethetask/ui/theme/Theme.kt
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
- Close #41
```
[x] Yes
[ ] No
```
-
> feat: カラーパレットの変更

- app/build.gradle
- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- Close #
```
[x] Yes
[ ] No
```
-
> feat: カード表示

- app/src/main/java/com/example/capturethetask/ui/home/HomeScreen.kt
- app/src/main/java/com/example/capturethetask/ui/theme/Color.kt
- Close #44
```
[x] Yes
[ ] No
```
-
> feat: デザイン改善
